# Generated by Django 6.1 on 2026-09-10 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('massege', models.TextField(blank=True, max_length=200)),
                ('numbers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScores',
            fields=[
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(default='toDelete', max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('game_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('userkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_scores',
            },
        ),
    ]
