# Generated by Django 5.2.7 on 2026-02-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScores',
            fields=[
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game_record_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'player_scores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='player_scores',
        ),
    ]
