# Generated by Django 5.2.7 on 2026-02-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0002_playerscores_delete_player_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerscores',
            options={'managed': True},
        ),
    ]
