# Generated by Django 6.0.4 on 2026-04-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0003_alter_playerscores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerscores',
            options={},
        ),
    ]
