# Generated by Django 6.0.4 on 2026-04-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0004_alter_playerscores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerscores',
            options={'managed': True},
        ),
    ]
