# Generated by Django 6.0.4 on 2026-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0005_alter_playerscores_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('massege', models.TextField(blank=True, max_length=200)),
                ('numbers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
