# Generated by Django 6.0.4 on 2026-06-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoard', '0006_testtable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscores',
            name='userkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='playerscores',
            name='name',
            field=models.CharField(default='toDelete', max_length=40),
        ),
        migrations.AlterField(
            model_name='playerscores',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
